/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package login;

import org.junit.Test;
import static org.junit.Assert.*;

public class LoginTest {
    @Test public void testAppHasAGreeting() {
        //Login classUnderTest = new Login();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
